import { motion } from 'framer-motion'
import { 
  Zap, 
  Globe, 
  TrendingUp, 
  Shield, 
  Sparkles, 
  BarChart3,
  FileText,
  Image,
  Share2
} from 'lucide-react'

export default function Features() {
  const features = [
    {
      icon: Zap,
      title: 'Lightning Fast Generation',
      description: 'Create SEO-optimized articles in 60 seconds with AI-powered research and writing',
      color: 'from-yellow-500 to-orange-500'
    },
    {
      icon: Globe,
      title: 'Multi-Region Support',
      description: 'Optimize content for any region with localized SERP research and geo-targeting',
      color: 'from-blue-500 to-cyan-500'
    },
    {
      icon: TrendingUp,
      title: '8 Powerful SEO Tools',
      description: 'Headline analyzer, readability checker, SERP preview, plagiarism detection & more',
      color: 'from-green-500 to-emerald-500'
    },
    {
      icon: BarChart3,
      title: 'Real-Time SEO Scoring',
      description: 'Get instant SEO scores with actionable insights to improve your rankings',
      color: 'from-purple-500 to-pink-500'
    },
    {
      icon: FileText,
      title: '12 Content Templates',
      description: 'Listicles, how-to guides, product reviews, case studies and more',
      color: 'from-red-500 to-rose-500'
    },
    {
      icon: Image,
      title: 'AI-Generated Images',
      description: 'Every article includes a beautiful hero image generated by AI',
      color: 'from-indigo-500 to-purple-500'
    },
    {
      icon: Share2,
      title: 'Social Media Posts',
      description: 'Auto-generate optimized posts for 9 platforms including LinkedIn, Twitter & TikTok',
      color: 'from-pink-500 to-rose-500'
    },
    {
      icon: Shield,
      title: 'Fact-Checked Content',
      description: 'Built-in plagiarism detection and citation tracking for E-E-A-T compliance',
      color: 'from-teal-500 to-cyan-500'
    }
  ]

  return (
    <section className="py-20 px-4">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl font-black mb-6">
            Everything You Need to <span className="gradient-text">Rank #1</span>
          </h2>
          <p className="text-xl text-white/70 max-w-3xl mx-auto">
            Powered by GPT-4 and Claude 3.5 Sonnet with real-time SERP research
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
              className="glass-strong rounded-2xl p-6 border border-white/10 hover:border-white/20 transition-all group"
            >
              <div className={`w-12 h-12 bg-gradient-to-br ${feature.color} rounded-xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                <feature.icon className="w-6 h-6 text-white" />
              </div>
              <h3 className="text-xl font-bold mb-3">{feature.title}</h3>
              <p className="text-white/70">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
